AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Arquitectura de procesamiento de facturas

Resources:
  # 1. Bucket de entrada (S3)
  BucketFacturas:
    Type: AWS::S3::Bucket

  # 2. Cola de mensajes (SQS) - El cuadro naranja de tu diagrama
  ColaProcesamiento:
    Type: AWS::SQS::Queue

  # 3. Base de datos (DynamoDB) - Donde guardas los resultados
  TablaResultados:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # 4. Función procesadora (Lambda) - El motor que une todo
  FuncionProcesadora:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        LlegadaMensaje:
          Type: SQS
          Properties:
            Queue: !GetAtt ColaProcesamiento.Arn